# Generated by Django 3.1 on 2020-09-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make',
            name='name',
        ),
    ]
