# Generated by Django 3.1 on 2020-09-19 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_remove_make_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='name',
            field=models.CharField(default=1234, help_text='Enter a value(e.g.Dodge)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'ENTER A BIG STRING')]),
            preserve_default=False,
        ),
    ]
