# Generated by Django 3.1 on 2020-10-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.category'),
        ),
        migrations.AddField(
            model_name='site',
            name='iso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.iso'),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.region'),
        ),
        migrations.AddField(
            model_name='site',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.state'),
        ),
    ]
