# Generated by Django 3.1 on 2020-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
